import { ServiceItem, Companion } from './types';

export const SERVICES: ServiceItem[] = [
  // Basic
  { id: 'srv_1', name: 'Coffee/Meal Date', category: 'Basic', basePrice: 500, perHourRate: 100 },
  { id: 'srv_2', name: 'Shopping Companion', category: 'Basic', basePrice: 2500, perHourRate: 350 },
  { id: 'srv_3', name: 'Movie/Café Hangout', category: 'Basic', basePrice: 500, perHourRate: 100 },
  { id: 'srv_4', name: 'Virtual Companion', category: 'Basic', basePrice: 1000, perHourRate: 200 },
  { id: 'srv_5', name: 'Language Practice', category: 'Basic', basePrice: 800, perHourRate: 150 },
  
  // Standard
  { id: 'srv_6', name: 'Dinner Date', category: 'Standard', basePrice: 5000, perHourRate: 500 },
  { id: 'srv_7', name: 'Event Companion', category: 'Standard', basePrice: 6000, perHourRate: 600 },
  { id: 'srv_8', name: 'Professional +1', category: 'Standard', basePrice: 8000, perHourRate: 700 },
  { id: 'srv_9', name: 'Cultural/Festival', category: 'Standard', basePrice: 5000, perHourRate: 500 },
  { id: 'srv_10', name: 'Hobby Partner', category: 'Standard', basePrice: 4000, perHourRate: 400 },
  
  // Premium
  { id: 'srv_11', name: 'Full Day Companion', category: 'Premium', basePrice: 10000, perHourRate: 800 },
  { id: 'srv_12', name: 'Travel Companion', category: 'Premium', basePrice: 12000, perHourRate: 1000 },
  { id: 'srv_13', name: 'Travel Guide', category: 'Premium', basePrice: 6000, perHourRate: 500 },
  { id: 'srv_14', name: 'Emotional Support', category: 'Premium', basePrice: 4000, perHourRate: 400 },
  
  // Exclusive
  { id: 'srv_15', name: 'Romantic Night', category: 'Exclusive', basePrice: 15000, perHourRate: 1200 },
  { id: 'srv_16', name: 'Weekend Companion', category: 'Exclusive', basePrice: 25000, perHourRate: 1500 },
  { id: 'srv_17', name: 'Vacation Companion', category: 'Exclusive', basePrice: 18000, perHourRate: 1200 }
];

// ALL PAKISTAN CITIES - Tier 1, 2, 3 based on 2023 Census
export const CITIES = {
  tier1: [
    'Karachi', 'Lahore', 'Islamabad', 'Rawalpindi', 'Faisalabad', 
    'Gujranwala', 'Multan', 'Hyderabad', 'Peshawar', 'Quetta'
  ],
  tier2: [
    'Sargodha', 'Sialkot', 'Bahawalpur', 'Jhang', 'Sheikhupura', 
    'Gujrat', 'Sukkur', 'Larkana', 'Sahiwal', 'Okara', 
    'Rahim Yar Khan', 'Kasur', 'Dera Ghazi Khan', 'Wah Cantonment', 
    'Mardan', 'Nawabshah (Benazirabad)', 'Burewala', 'Mingora', 
    'Hafizabad', 'Chiniot', 'Jhelum', 'Kamoke', 'Khanewal', 
    'Sadiqabad', 'Turbat', 'Mirpur Khas', 'Muridke', 'Khanpur', 
    'Bahawalnagar', 'Kohat', 'Muzaffargarh', 'Abbottabad', 
    'Mandi Bahauddin', 'Daska', 'Pakpattan', 'Dera Ismail Khan', 
    'Jacobabad', 'Chakwal', 'Khuzdar', 'Gojra', 'Vehari', 
    'Shikarpur', 'Ahmedpur East', 'Hub', 'Chishtian', 'Khairpur', 
    'Dadu', 'Samundri', 'Ferozwala', 'Attock', 'Tando Adam', 
    'Tando Allahyar', 'Jaranwala', 'Bholari', 'Muzaffarabad', 
    'Hasilpur', 'Kamalia', 'Kot Abdul Malik', 'Panjgur', 'Arif Wala', 
    'Gujranwala Cantonment', 'Swabi', 'Jampur', 'Jatoi', 'Wazirabad', 
    'Layyah', 'Shujabad', 'Haroonabad', 'Jalalpur Jattan', 'Umerkot', 
    'Lodhran', 'Moro', 'Kot Addu', 'Mian Channu', 'Khushab', 
    'Rajanpur', 'Mansehra', 'Taxila', 'Mirpur', 'Kabal', 'Bhakkar', 
    'Narowal', 'Chaman', 'Mianwali', 'Shakargarh', 'Mailsi', 
    'Nowshera', 'Dipalpur', 'Haveli Lakha', 'Lala Musa', 'Shahdadkot', 
    'Charsadda', 'Ghotki', 'Sambrial', 'Bhalwal', 'Badin', 'Taunsa', 
    'Barikot', 'Phool Nagar', 'Tando Muhammad Khan', 'Pattoki', 
    'Shahdadpur', 'Jauharabad', 'Kamber Ali Khan', 'Chichawatni', 
    'Farooqabad', 'Pishin', 'Dera Murad Jamali', 'Kotri', 
    'Sangla Hill', 'Gujar Khan', 'Kharian', 'Pasrur', 'Shabqadar'
  ],
  tier3: [
    'Saidu Sharif', 'Matta', 'Kalam', 'Fizagat', 'Charbagh', 'Utror', 
    'Minglawar', 'Chuprial', 'Takht Bhai', 'Katlang', 'Rustam', 
    'Baghdada', 'Gujar Garhi', 'Lund Khwar', 'Shahbaz Garhi', 'Toru', 
    'Bahri', 'Havelian', 'Lora', 'Sheikhul Bandi', 'Salhad', 
    'Mansehra Road Towns', 'Qalandarabad', 'Nawan Shehr', 'Dhamtore', 
    'Balakot', 'Oghi', 'Baffa', 'Shinkiari', 'Garhi Habibullah', 
    'Kaghan', 'Naran', 'Battal', 'Ichrian', 'Haripur City', 'Ghazi', 
    'Sirikot', 'Hattar', 'Khalabat Township', 'Kot Najibullah', 'Baldher', 
    'Shabqadar', 'Tangi', 'Utmanzai', 'Rajjar', 'Nisatta', 'Umarzai', 
    'Sherpao', 'Akora Khattak', 'Pabbi', 'Jehangira', 'Rashakai', 
    'Azakhel', 'Amangarh', 'Ziarat Kaka Sahib', 'Topi', 'Razar', 
    'Chota Lahore', 'Shah Mansoor', 'Gohati', 'Maneri', 'Yar Hussain', 
    'Kalabat', 'Lachi', 'Gumbat', 'Jarma', 'Ustarzai', 'Shakardarra', 
    'Domel', 'Kakki', 'Miryan', 'Ghoriwala', 'Mandan', 'Sokari', 
    'Janikhel', 'Kulachi', 'Paharpur', 'Chashma Town', 'Daraban', 
    'Paniala', 'Lakki', 'Serai Naurang', 'Abbasa Khel', 'Tajori', 'Pezu', 
    'Tank City', 'Gomal', 'Muhammadzai', 'Mullazai', 'Banda Daudshah', 
    'Takht-e-Nasrati', 'Latamber', 'Teri', 'Jatta Ismail Khel', 
    'Allai', 'Kuza Banda', 'Thakot', 'Bana', 'Alpuri', 'Puran', 'Besham', 
    'Karora', 'Shahpur', 'Chakisar', 'Dir Town', 'Wari', 'Thal', 
    'Barawal', 'Jandari', 'Timergara', 'Chakdara', 'Maidan', 'Talash', 
    'Khall', 'Munda', 'Adenzai', 'Batkhela', 'Dargai', 'Thana', 
    'Alladand', 'Sakhakot', 'Daggar', 'Sawari', 'Sultanwas', 'Pir Baba', 
    'Chinglai', 'Hangu City', 'Thall', 'Doaba', 'Togh Bala', 'Kalaya', 
    'Hangu-Orakzai belt', 'Ghiljo', 'Mishti', 'Khanzai', 'Parachinar', 
    'Sadda', 'Alizai', 'Pewar', 'Tari Mangal', 'Shalozan', 'Miranshah', 
    'Mir Ali', 'Boya', 'Spinwam', 'Razmak', 'Datta Khel', 'Ghulam Khan', 
    'Wana', 'Shakai', 'Ladha', 'Makeen', 'Sararogha', 'Gilgit', 'Skardu', 
    'Hunza', 'Chilas', 'Astore', 'Kharmang', 'Shigar', 'Nagar', 'Ghanche', 
    'Diamer', 'Ghizer', 'Bagh', 'Rawalakot', 'Pallandri', 'Kotli', 
    'Bhimber', 'Hattian Bala', 'Hajira', 'Athmuqam', 'Chakswari', 
    'Dadyal', 'Islamgarh', 'Mehmoodabad', 'Khuiratta', 'Nakyal', 
    'Sehnsa', 'Tattar Pani', 'Tandali', 'Thorar', 'Trarkhal', 
    'Thana Mandi', 'Kotli Sattian', 'Murree', 'Kahuta', 'Kallar Syedan', 
    'Kotli', 'Kohat', 'Lachi', 'Hangu', 'Thall', 'Doaba', 'Togh Bala', 
    'Bannu', 'Lakki Marwat', 'Tank', 'Karak', 'Kohat', 'Hangu', 'Bajaur', 
    'Mohmand', 'Khyber', 'Kurram', 'Orakzai', 'North Waziristan', 
    'South Waziristan', 'Zhob', 'Loralai', 'Musa Khel', 'Barkhan', 
    'Qila Saifullah', 'Sherani', 'Killa Abdullah', 'Chagai', 'Nushki', 
    'Washuk', 'Kharan', 'Panjgur', 'Awaran', 'Kech', 'Gwadar', 'Lasbela', 
    'Khuzdar', 'Kalat', 'Mastung', 'Sibi', 'Ziarat', 'Harnai', 'Dera Bugti', 
    'Jhal Magsi', 'Kachhi', 'Nasirabad', 'Jaffarabad', 'Sohbatpur', 
    'Usta Muhammad', 'Gandava', 'Chaman', 'Pishin', 'Killa Abdullah', 
    'Qila Saifullah', 'Loralai', 'Barkhan', 'Musa Khel', 'Zhob', 'Sherani', 
    'Duki', 'Harnai', 'Ziarat', 'Sibi', 'Kohlu', 'Dera Bugti', 'Jhal Magsi', 
    'Kachhi', 'Nasirabad', 'Sohbatpur', 'Usta Muhammad', 'Jaffarabad', 
    'Gandava', 'Hub', 'Uthal', 'Bela', 'Sonmiani', 'Ormara', 'Pasni', 
    'Jiwani', 'Gwadar', 'Turbat', 'Panjgur', 'Chagai', 'Nushki', 'Kharan', 
    'Washuk', 'Awaran', 'Kech', 'Khuzdar', 'Kalat', 'Mastung', 'Wadh', 
    'Surab', 'Bagh', 'Rawalakot', 'Pallandri', 'Kotli', 'Bhimber', 
    'Hattian Bala', 'Hajira', 'Athmuqam', 'Chakswari', 'Dadyal', 
    'Islamgarh', 'Mehmoodabad', 'Khuiratta', 'Nakyal', 'Sehnsa', 
    'Tattar Pani', 'Tandali', 'Thorar', 'Trarkhal', 'Thana Mandi', 
    'Kotli Sattian', 'Murree', 'Kahuta', 'Kallar Syedan', 'Kotli', 
    'Dina', 'Jhelum', 'Sohawa', 'Pind Dadan Khan', 'Khewra', 'Bhalwal', 
    'Sargodha', 'Kot Momin', 'Sahiwal', 'Shahpur', 'Bhera', 'Silanwali', 
    'Farooqabad', 'Sheikhupura', 'Muridke', 'Ferozewala', 'Safdarabad', 
    'Sharak Pur', 'Nankana Sahib', 'Sangla Hill', 'Chiniot', 'Bhawana', 
    'Kot Shakir', 'Lalian', 'Rabwah', 'Mandi Bahauddin', 'Malakwal', 
    'Phalia', 'Dinga', 'Kunjah', 'Shadiwal', 'Wazirabad', 'Alipur Chatha', 
    'Zahir Pir', 'Khanpur', 'Liaquatpur', 'Sadiqabad', 'Dera Ghazi Khan', 
    'Kot Chutta', 'Taunsa', 'Koh-e-Suleman', 'Rajanpur', 'Jampur', 
    'Dajal', 'Harrand', 'Muzaffargarh', 'Khangarh', 'Mehmood Kot', 
    'Jatoi', 'Alipur', 'Kot Addu', 'Layyah', 'Karor Lal Esan', 'Chaubara', 
    'Bhakkar', 'Darya Khan', 'Kaloorkot', 'Mankera', 'Mianwali', 'Isa Khel', 
    'Piplan', 'Kundian', 'Harnoli', 'Talagang', 'Lawa', 'Multan', 
    'Shujabad', 'Jalalpur Pirwala', 'Qadirpur Ran', 'Mailsi', 'Vehari', 
    'Burewala', 'Mian Channu', 'Kabirwala', 'Toba Tek Singh', 'Gojra', 
    'Kamalia', 'Pir Mahal', 'Chichawatni', 'Sahiwal', 'Okara', 'Renala Khurd', 
    'Depalpur', 'Hujra', 'Basirpur', 'Faisalabad', 'Jaranwala', 'Samundri', 
    'Tandlianwala', 'Khurrianwala', 'Chak Jhumra', 'Sargodha', 'Kot Momin', 
    'Bhalwal', 'Sillanwali', 'Shahpur', 'Miani', 'Lahore', 'Kasur', 
    'Raiwind', 'Kot Lakhpat', 'Wagah', 'Shalimar', 'Gujranwala', 'Kamoke', 
    'Nowshera Virkan', 'Wazirabad', 'Qila Didar Singh', 'Nandipur', 
    'Gujrat', 'Lala Musa', 'Kharian', 'Jalalpur Jattan', 'Kunjah', 
    'Sarai Alamgir', 'Sialkot', 'Daska', 'Sambrial', 'Ugoke', 'Pasrur', 
    'Shakargarh', 'Narowal', 'Shakargarh', 'Zafarwal', 'Sahowala', 
    'Chawinda', 'Baddomalhi', 'Narowal', 'Zafarwal', 'Sialkot', 'Daska', 
    'Sambrial', 'Pasrur', 'Shakargarh', 'Rawalpindi', 'Taxila', 'Wah', 
    'Gujar Khan', 'Kallar Syedan', 'Kahuta', 'Murree', 'Kotli Sattian', 
    'Islamabad', 'Attock', 'Fateh Jang', 'Hassan Abdal', 'Jand', 'Pindi Gheb', 
    'Hazro', 'Kamra', 'Basal', 'Narian', 'Karak', 'Takht-e-Nasrati', 
    'Banda Daud Shah', 'Latamber', 'Kohat', 'Lachi', 'Hangu', 'Thall', 
    'Doaba', 'Togh Bala', 'Karak', 'Bannu', 'Domel', 'Kakki', 'Miryan', 
    'Ghoriwala', 'Mandan', 'Sokari', 'Janikhel', 'Lakki Marwat', 'Serai Naurang', 
    'Abbasa Khel', 'Tajori', 'Pezu', 'Dera Ismail Khan', 'Kulachi', 'Paharpur', 
    'Chashma', 'Daraban', 'Paniala', 'Tank', 'Gomal', 'Muhammadzai', 'Mullazai', 
    'Mardan', 'Takht Bhai', 'Katlang', 'Rustam', 'Baghdada', 'Gujar Garhi', 
    'Lund Khwar', 'Shahbaz Garhi', 'Toru', 'Bahri', 'Swabi', 'Topi', 'Razar', 
    'Chota Lahore', 'Shah Mansoor', 'Gohati', 'Maneri', 'Yar Hussain', 
    'Kalabat', 'Nowshera', 'Pabbi', 'Jehangira', 'Rashakai', 'Azakhel', 
    'Amangarh', 'Ziarat Kaka Sahib', 'Charsadda', 'Shabqadar', 'Tangi', 
    'Utmanzai', 'Rajjar', 'Nisatta', 'Umarzai', 'Sherpao', 'Peshawar', 
    'Chamkani', 'Badaber', 'Hayatabad', 'Tehkal', 'Palosi', 'Shaheen Town', 
    'Pishtakhara', 'Hazarkhwani', 'Regi Lalma', 'Urmar Miana', 'Abbottabad', 
    'Havelian', 'Lora', 'Sheikhul Bandi', 'Salhad', 'Qalandarabad', 'Nawan Shehr', 
    'Dhamtore', 'Mansehra', 'Balakot', 'Oghi', 'Baffa', 'Shinkiari', 
    'Garhi Habibullah', 'Kaghan', 'Naran', 'Battal', 'Ichrian', 'Haripur', 
    'Khanpur', 'Ghazi', 'Sirikot', 'Hattar', 'Khalabat Township', 'Kot Najibullah', 
    'Baldher', 'Kohistan', 'Dassu', 'Pattan', 'Palas', 'Bahrain', 'Madaklasht', 
    'Chitral', 'Booni', 'Mastuj', 'Garam Chashma', 'Arandu', 'Bumburet', 
    'Rumbur', 'Kalash', 'Parachinar', 'Sadda', 'Alizai', 'Pewar', 'Tari Mangal', 
    'Shalozan', 'Miranshah', 'Mir Ali', 'Boya', 'Spinwam', 'Razmak', 
    'Datta Khel', 'Ghulam Khan', 'Wana', 'Shakai', 'Ladha', 'Makeen', 
    'Sararogha', 'Mingora', 'Saidu Sharif', 'Matta', 'Kabal', 'Kalam', 
    'Fizagat', 'Charbagh', 'Utror', 'Minglawar', 'Chuprial', 'Bahrain', 
    'Barikot', 'Khwazakhela', 'Buner', 'Daggar', 'Sawari', 'Sultanwas', 
    'Pir Baba', 'Chinglai', 'Malakand', 'Batkhela', 'Dargai', 'Thana', 
    'Alladand', 'Sakhakot', 'Shangla', 'Alpuri', 'Puran', 'Besham', 'Karora', 
    'Shahpur', 'Chakisar', 'Upper Dir', 'Dir Town', 'Wari', 'Thal', 'Barawal', 
    'Jandari', 'Lower Dir', 'Timergara', 'Chakdara', 'Maidan', 'Talash', 
    'Khall', 'Munda', 'Adenzai', 'Swat', 'Mingora', 'Saidu Sharif', 'Matta', 
    'Kabal', 'Kalam', 'Fizagat', 'Charbagh', 'Utror', 'Minglawar', 'Chuprial', 
    'Torghar', 'Judba', 'Kandar', 'Gulistan', 'Sherani', 'Zhob', 'Loralai', 
    'Barkhan', 'Musa Khel', 'Duki', 'Harnai', 'Ziarat', 'Sibi', 'Kohlu', 
    'Dera Bugti', 'Jhal Magsi', 'Kachhi', 'Nasirabad', 'Sohbatpur', 
    'Usta Muhammad', 'Jaffarabad', 'Gandava', 'Hub', 'Uthal', 'Bela', 
    'Sonmiani', 'Ormara', 'Pasni', 'Jiwani', 'Gwadar', 'Turbat', 'Panjgur', 
    'Chagai', 'Nushki', 'Kharan', 'Washuk', 'Awaran', 'Kech', 'Khuzdar', 
    'Kalat', 'Mastung', 'Wadh', 'Surab', 'Quetta', 'Pishin', 'Killa Abdullah', 
    'Chaman', 'Qila Saifullah', 'Loralai', 'Barkhan', 'Musa Khel', 'Zhob', 
    'Sherani', 'Duki', 'Harnai', 'Ziarat', 'Sibi', 'Kohlu', 'Dera Bugti', 
    'Jhal Magsi', 'Kachhi', 'Nasirabad', 'Sohbatpur', 'Usta Muhammad', 
    'Jaffarabad', 'Gandava', 'Karachi', 'Hyderabad', 'Sukkur', 'Larkana', 
    'Nawabshah', 'Mirpur Khas', 'Jacobabad', 'Shikarpur', 'Khairpur', 
    'Dadu', 'Tando Adam', 'Tando Allahyar', 'Tando Muhammad Khan', 
    'Badin', 'Thatta', 'Sujawal', 'Umerkot', 'Mithi', 'Diplo', 'Chachro', 
    'Nagarparkar', 'Islamkot', 'Tharparkar', 'Sanghar', 'Khipro', 'Shahdadpur', 
    'Sinjhoro', 'Tando Bago', 'Mirpur Bathoro', 'Jati', 'Kamber Ali Khan', 
    'Shahdadkot', 'Qambar', 'Mirokhan', 'Warah', 'Nasirabad', 'Mehar', 
    'Dadu', 'Johi', 'Mehar', 'Khairpur Nathan Shah', 'Sehwan', 'Thatta', 
    'Sujawal', 'Keti Bandar', 'Jati', 'Kharo Chan', 'Gharo', 'Mirpur Sakro', 
    'Dhabeji', 'Thano Bula Khan', 'Kotri', 'Hyderabad', 'Tando Jam', 
    'Tando Qaiser', 'Matli', 'Bulri Shah Karim', 'Hala', 'Saeedabad', 
    'Bhit Shah', 'Hala', 'Matiari', 'New Saeedabad', 'Tando Ghulam Hyder', 
    'Chuhar Jamali', 'Daro', 'Jhudo', 'Digri', 'Kunri', 'Samaro', 
    'Umarkot', 'Pithoro', 'Nabisar', 'Sinjhoro', 'Khipro', 'Sanghar', 
    'Shahdadpur', 'Tando Adam', 'Nawabshah', 'Daur', 'Bandhi', 'Moro', 
    'Daulatpur', 'Naushero Feroze', 'Bhiria', 'Mehrabpur', 'Tharu Shah', 
    'Pad Idan', 'Kandiaro', 'Bhirya City', 'Darya Khan Marri', 'Sakrand', 
    'Daulatpur', 'Kot Diji', 'Fareedabad', 'Gambat', 'Ranipur', 'Hingorja', 
    'Khairpur', 'Kot Diji', 'Thari Mirwah', 'Sobho Dero', 'Mirokhan', 
    'Warah', 'Nasirabad', 'Qambar', 'Shahdadkot', 'Sijawal Junejo', 
    'Mirokhan', 'Lakhi', 'Ghulam Shah Bagrani', 'Kandhkot', 'Kashmore', 
    'Tangwani', 'Ghouspur', 'Kandhkot', 'Bakhshapur', 'Guddu', 'Thul', 
    'Jacobabad', 'Garhi Khairo', 'Thul', 'Qubo Saeed Khan', 'Kandhkot', 
    'Kashmore', 'Tangwani', 'Ghouspur', 'Bakhshapur', 'Guddu', 'Ubauro', 
    'Mirpur Mathelo', 'Daharki', 'Ghotki', 'Khanpur Mahar', 'Mirpur Mathelo', 
    'Daharki', 'Sobho Dero', 'Thari Mirwah', 'Khairpur Nathan Shah', 
    'Sehwan Sharif', 'Manjhand', 'Bhan Saeedabad', 'Sehwan', 'Dadu', 
    'Johi', 'Mehar', 'Khairpur Nathan Shah', 'Johi', 'Mehar', 'Dadu', 
    'Khairpur', 'Kot Diji', 'Thari Mirwah', 'Sobho Dero', 'Mirokhan', 
    'Warah', 'Nasirabad', 'Qambar', 'Shahdadkot', 'Sijawal Junejo', 
    'Lakhi', 'Ghulam Shah Bagrani', 'Kandhkot', 'Kashmore', 'Tangwani', 
    'Ghouspur', 'Kandhkot', 'Bakhshapur', 'Guddu', 'Thul', 'Jacobabad', 
    'Garhi Khairo', 'Qubo Saeed Khan', 'Ubauro', 'Mirpur Mathelo', 
    'Daharki', 'Ghotki', 'Khanpur Mahar', 'Sukkur', 'Rohri', 'Pano Aqil', 
    'Ghauspur', 'Salehpat', 'Sukkur', 'New Sukkur', 'Rohri', 'Pano Aqil', 
    'Ghauspur', 'Ghotki', 'Mirpur Mathelo', 'Daharki', 'Khanpur Mahar', 
    'Ubauro', 'Sukkur', 'Larkana', 'Ratodero', 'Naudero', 'Mirokhan', 
    'Bakrani', 'Dokri', 'Badah', 'Larkana', 'Kamber', 'Shahdadkot', 
    'Qambar', 'Mirokhan', 'Warah', 'Nasirabad', 'Mehar', 'Dadu', 'Johi', 
    'Mehar', 'Khairpur Nathan Shah', 'Sehwan', 'Thatta', 'Sujawal', 
    'Keti Bandar', 'Jati', 'Kharo Chan', 'Gharo', 'Mirpur Sakro', 
    'Dhabeji', 'Thano Bula Khan', 'Kotri', 'Hyderabad', 'Tando Jam', 
    'Tando Qaiser', 'Matli', 'Bulri Shah Karim', 'Hala', 'Saeedabad', 
    'Bhit Shah', 'Matiari', 'New Saeedabad', 'Tando Ghulam Hyder', 
    'Chuhar Jamali', 'Daro', 'Jhudo', 'Digri', 'Kunri', 'Samaro', 
    'Umarkot', 'Pithoro', 'Nabisar', 'Sinjhoro', 'Khipro', 'Sanghar', 
    'Shahdadpur', 'Tando Adam', 'Nawabshah', 'Daur', 'Bandhi', 'Moro', 
    'Daulatpur', 'Naushero Feroze', 'Bhiria', 'Mehrabpur', 'Tharu Shah', 
    'Pad Idan', 'Kandiaro', 'Bhirya City', 'Darya Khan Marri', 'Sakrand', 
    'Kot Diji', 'Fareedabad', 'Gambat', 'Ranipur', 'Hingorja', 'Khairpur', 
    'Thari Mirwah', 'Sobho Dero', 'Lakhi', 'Ghulam Shah Bagrani', 
    'Kandhkot', 'Kashmore', 'Tangwani', 'Ghouspur', 'Bakhshapur', 
    'Guddu', 'Thul', 'Garhi Khairo', 'Qubo Saeed Khan', 'Ubauro', 
    'Mirpur Mathelo', 'Daharki', 'Khanpur Mahar', 'Rohri', 'Pano Aqil', 
    'Ghauspur', 'Salehpat', 'New Sukkur', 'Ratodero', 'Naudero', 
    'Bakrani', 'Dokri', 'Badah', 'Kamber', 'Sijawal Junejo', 'Lakhi'
  ]
};

// Flatten all cities for dropdown use
export const ALL_CITIES = [...CITIES.tier1, ...CITIES.tier2, ...CITIES.tier3];

export const INTEREST_OPTIONS = [
  'Dining', 'Travel', 'Events', 'Conversation', 'Hobbies', 
  'Gaming', 'Movies', 'Books', 'Music', 'Fitness', 'Art'
];

export const SEED_COMPANIONS: Companion[] = [
  {
    id: 'comp_1',
    name: 'Aisha Khan',
    age: 24,
    gender: 'Female',
    city: 'Lahore',
    bio: 'Avid reader, movie enthusiast, and conversationalist. I love exploring new cafes in Lahore, sharing stories, and practicing different languages over a warm cup of tea. Looking forward to professional meetups or shopping hangout guidance!',
    interests: ['Dining', 'Conversation', 'Movies', 'Books'],
    photos: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=400'
    ],
    services: [
      { serviceId: 'srv_1' },
      { serviceId: 'srv_3' },
      { serviceId: 'srv_5' },
      { serviceId: 'srv_10' }
    ],
    rating: 4.9,
    reviews: [
      {
        id: 'rev_1_1',
        reviewerName: 'Kamran Ali',
        rating: 5,
        comment: 'Aisha is an incredibly polite and well-spoken guide. We enjoyed a great conversation and coffee in DHA Lahore.',
        date: '2026-06-15'
      },
      {
        id: 'rev_1_2',
        reviewerName: 'Zara Sheikh',
        rating: 4.8,
        comment: 'Wonderful experience practicing Spanish and English language terms. Super patient and intellectual.',
        date: '2026-07-02'
      }
    ],
    status: 'Approved',
    isVerified: true
  },
  {
    id: 'comp_2',
    name: 'Zain Ahmed',
    age: 26,
    gender: 'Male',
    city: 'Karachi',
    bio: 'Fitness trainer, music producer, and food explorer. I know the absolute best places in Karachi for shopping and dinner dates. Let me accompany you to your next social event or help you find authentic local street food!',
    interests: ['Dining', 'Travel', 'Fitness', 'Music', 'Events'],
    photos: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=400'
    ],
    services: [
      { serviceId: 'srv_2' },
      { serviceId: 'srv_6' },
      { serviceId: 'srv_7' },
      { serviceId: 'srv_11' }
    ],
    rating: 4.8,
    reviews: [
      {
        id: 'rev_2_1',
        reviewerName: 'Bilal Butt',
        rating: 5,
        comment: 'Very professional. Assisted me during some heavy shopping at Clifton Mall and recommended outstanding spots.',
        date: '2026-06-20'
      }
    ],
    status: 'Approved',
    isVerified: true
  },
  {
    id: 'comp_3',
    name: 'Sana Malik',
    age: 25,
    gender: 'Female',
    city: 'Islamabad',
    bio: 'Freelance designer and cultural enthusiast. Extremely passionate about Pakistani festivals, travel, and emotional support. I offer professional +1 companionship and curated cultural city guides in Rawalpindi/Islamabad.',
    interests: ['Travel', 'Art', 'Conversation', 'Events', 'Hobbies'],
    photos: [
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=400',
      'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&q=80&w=400',
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&q=80&w=400'
    ],
    services: [
      { serviceId: 'srv_8' },
      { serviceId: 'srv_9' },
      { serviceId: 'srv_13' },
      { serviceId: 'srv_14' }
    ],
    rating: 5.0,
    reviews: [
      {
        id: 'rev_3_1',
        reviewerName: 'Dr. Sameer',
        rating: 5,
        comment: 'Sana was my professional +1 for a medical conference dinner. Exceptional etiquette and brilliant socializing skills.',
        date: '2026-05-11'
      }
    ],
    status: 'Approved',
    isVerified: true
  },
  {
    id: 'comp_4',
    name: 'Hamza Ali',
    age: 27,
    gender: 'Male',
    city: 'Multan',
    bio: 'An outgoing host and local expert. Love guiding people through Multan\'s rich spiritual and historic festival sites, tasting famous local sweets, or joining as an enthusiast for weekend getaways and vacation tours.',
    interests: ['Travel', 'Dining', 'Hobbies', 'Events'],
    photos: [
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=400',
      'https://images.unsplash.com/photo-1489980508314-941910ded1f4?auto=format&fit=crop&q=80&w=400',
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400'
    ],
    services: [
      { serviceId: 'srv_9' },
      { serviceId: 'srv_12' },
      { serviceId: 'srv_16' }
    ],
    rating: 4.7,
    reviews: [],
    status: 'Approved',
    isVerified: true
  }
];
